---
title: "Seafood Dashboard poc"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(lubridate)
library(vroom)
library(tidyverse)
```

```{r loading data, include=FALSE}

df_Seafood <- vroom("TradeData_HMRC_Preliminary-Cleaned.csv")
```

```{r Data processing, include=FALSE}
##### Turning Character columns in Factors. But first selecting all columns of class = Character
# https://stackoverflow.com/questions/33180058/coerce-multiple-columns-to-factors-at-once
df_Seafood[map_lgl(df_Seafood, is.character)] <- lapply(df_Seafood[map_lgl(df_Seafood, is.character)], factor)

#### turning Year in to date.year
## Issue here. We only have years, and that is not a valid date format for plotting. But, since the values are annual sum. But, for plotting it looks better using the 1st of Jan. If we would use e.g. the 31.12.2019, it would look like the data is for 2020 :( 

df_Seafood$Year <-dmy(as.character(paste("01-01",df_Seafood$Year)))
```


Row 
-----------------------------------------------------------------------

### Chart 1 Annual Plot

```{r}
ggplot(df_Seafood, aes(Year,Value))+
      geom_line(aes(colour = SpeciesType))

```

### Legend

```{r Plot legend lives here}
# legend needs to be

```


Row 
-----------------------------------------------------------------------

### Data Table

```{r}

```

### Select input

```{r}

```

